version: '3.8'

services: 

  mongo:
    image: mongo
    container_name: mongo
    # command: mongod --storageEngine=wiredTiger
    # ports: 
      # - 27017:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: mongo
    # volumes: 
      # - ./data:/data/db
    networks:
      - reaction-network

  reaction:
    image: reactioncommerce/reaction
    container_name: reaction
    depends_on: 
      - mongo
    ports: 
      - 80:3000
    environment: 
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://mongo:27017/reaction"
      REACTION_EMAIL: "dgil@mincer.es"
      REACTION_USER: "dgil"
      REACTION_AUTH: "123asd"
    networks:
      - reaction-network

networks:
  reaction-network: