version: '3.8'

services: 

  web:
    image: joomla
    container_name: joomla-web
    volumes: 
      - joomla:/var/www/html
    environment: 
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_NAME: joomla
    ports: 
      - 8080:80

  mysql:
    image: mysql:5.7
    container_name: joomla-mysql
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: joomla
      MYSQL_DATABASE: joomla
      MYSQL_PASSWORD: joomla

volumes: 
  joomla: